<?php

use Illuminate\Database\Seeder;

class sc_project extends Seeder {

    public function run() {
        $sc_project = [
            0 => [
                'name' => 'Projeto TCC - Scrummer',
                'id_status' => '2', //Em Andamento
                'description' => 'Criação de um software para gerenciamento de projetos Scrum com gamificação',
                'start_date' => '2017-01-01',
                'end_date' => '2017-11-01',
            ],
1=> ['name' => 'Fraseologia Gestor Outro Celular - Meu Vivo PJ Móvel','id_status' => '5','description' => 'Fraseologia Gestor Outro Celular - Meu Vivo PJ Móvel','start_date' => '2017-01-02','end_date' => '2017-07-01',],
2=> ['name' => 'Campanha 0500 ¿Uma História de vida construída entre amigos','id_status' => '5','description' => 'Campanha 0500 ¿Uma História de vida construída entre amigos','start_date' => '2017-01-02','end_date' => '2017-07-01',],
3=> ['name' => 'Indicador IAP ¿ TV e SMP-14.','id_status' => '5','description' => 'Indicador IAP ¿ TV e SMP-14.','start_date' => '2017-01-02','end_date' => '2017-07-01',],
4=> ['name' => 'Atualização Valor da Fatura Status Pendente - Web e Site Mobile','id_status' => '5','description' => 'Atualização Valor da Fatura Status Pendente - Web e Site Mobile','start_date' => '2017-01-02','end_date' => '2017-07-01',],
5=> ['name' => 'TDATA Parte 1 - Parametrizar no SAP todos os CFOPs de Venda e devoluções','id_status' => '5','description' => 'TDATA Parte 1 - Parametrizar no SAP todos os CFOPs de Venda e devoluções','start_date' => '2017-01-02','end_date' => '2017-07-01',],
6=> ['name' => 'TDATA Parte 2 - Parametrizações de novos NCM´s e alíquotas','id_status' => '5','description' => 'TDATA Parte 2 - Parametrizações de novos NCM´s e alíquotas','start_date' => '2017-01-02','end_date' => '2017-07-01',],
7=> ['name' => 'VOLTE E VOWIFI','id_status' => '5','description' => 'VOLTE E VOWIFI','start_date' => '2017-01-03','end_date' => '2017-07-02',],
8=> ['name' => 'Migração de Plataformas de Rede Inteligente','id_status' => '5','description' => 'Migração de Plataformas de Rede Inteligente','start_date' => '2017-01-03','end_date' => '2017-07-02',],
9=> ['name' => 'Projeto Rita','id_status' => '5','description' => 'Projeto Rita','start_date' => '2017-01-03','end_date' => '2017-07-02',],
10=> ['name' => '[DEX B2C Gestão Saldo] Simplificar informações sobre promoções no Meu Vivo WEB e Site mobile','id_status' => '5','description' => '[DEX B2C Gestão Saldo] Simplificar informações sobre promoções no Meu Vivo WEB e Site mobile','start_date' => '2017-01-03','end_date' => '2017-07-02',],
11=> ['name' => 'Melhorias Inventário Science - Setembro parte 2','id_status' => '5','description' => 'Melhorias Inventário Science - Setembro parte 2','start_date' => '2017-01-04','end_date' => '2017-07-03',],
12=> ['name' => 'Disponibilização do servidor para indicadores OSS','id_status' => '5','description' => 'Disponibilização do servidor para indicadores OSS','start_date' => '2017-01-04','end_date' => '2017-07-03',],
13=> ['name' => '[RGC] Acesso ao sistemas GPS e SIEBEL nas Lojas Próprias (Vivo1)','id_status' => '5','description' => '[RGC] Acesso ao sistemas GPS e SIEBEL nas Lojas Próprias (Vivo1)','start_date' => '2017-01-04','end_date' => '2017-07-03',],
14=> ['name' => 'Vivo Controle B2B','id_status' => '5','description' => 'Vivo Controle B2B','start_date' => '2017-01-02','end_date' => '2017-07-01',],
15=> ['name' => 'Alterar código de interfaces e do próprio SCAI.','id_status' => '5','description' => 'Alterar código de interfaces e do próprio SCAI.','start_date' => '2017-01-02','end_date' => '2017-07-01',],
16=> ['name' => 'Ambiente de Testes e Homologação ¿ Massivo FRAUDEVIEW','id_status' => '5','description' => 'Ambiente de Testes e Homologação ¿ Massivo FRAUDEVIEW','start_date' => '2017-01-03','end_date' => '2017-07-02',],
17=> ['name' => 'UnFrida Móvel B2B - Novos Planos Portfólio SmartVivo Empresas - Complementar','id_status' => '5','description' => 'UnFrida Móvel B2B - Novos Planos Portfólio SmartVivo Empresas - Complementar','start_date' => '2017-01-03','end_date' => '2017-07-02',],
18=> ['name' => 'Reprocessamento para incluir bonus para clientes FRIDA','id_status' => '5','description' => 'Reprocessamento para incluir bonus para clientes FRIDA','start_date' => '2017-01-05','end_date' => '2017-07-04',],
19=> ['name' => '[DEX B2B Billing] Opt In Conta Digital massivo por CNPJ - Gestor Móvel PJ','id_status' => '5','description' => '[DEX B2B Billing] Opt In Conta Digital massivo por CNPJ - Gestor Móvel PJ','start_date' => '2017-01-05','end_date' => '2017-07-04',],
20=> ['name' => 'Melhorias Ambiente de Homologação e Desenvolvimento Pro-Siga','id_status' => '5','description' => 'Melhorias Ambiente de Homologação e Desenvolvimento Pro-Siga','start_date' => '2017-01-05','end_date' => '2017-07-04',],
21=> ['name' => 'Conectividade para Garantia de Receita - Frentes:CSO   FAT  SGS e SIU','id_status' => '5','description' => 'Conectividade para Garantia de Receita - Frentes:CSO   FAT  SGS e SIU','start_date' => '2017-01-06','end_date' => '2017-07-05',],
22=> ['name' => 'Conectividade para Garantia de Receita ¿ frente Mediação Fase 2','id_status' => '5','description' => 'Conectividade para Garantia de Receita ¿ frente Mediação Fase 2','start_date' => '2017-01-06','end_date' => '2017-07-05',],
23=> ['name' => '[DEX B2B Billing] Relatorio de log s de acesso Meu Vivo WEB PJ','id_status' => '5','description' => '[DEX B2B Billing] Relatorio de log s de acesso Meu Vivo WEB PJ','start_date' => '2017-01-06','end_date' => '2017-07-05',],
24=> ['name' => 'Biometria Voz - Insumos para alerta','id_status' => '5','description' => 'Biometria Voz - Insumos para alerta','start_date' => '2017-01-09','end_date' => '2017-07-08',],
25=> ['name' => 'Alocação de Storage para ePO','id_status' => '5','description' => 'Alocação de Storage para ePO','start_date' => '2017-01-05','end_date' => '2017-07-04',],
26=> ['name' => 'Redirect 301 definitivo - Portal Vivo','id_status' => '5','description' => 'Redirect 301 definitivo - Portal Vivo','start_date' => '2017-01-06','end_date' => '2017-07-05',],
27=> ['name' => 'Infância Controle PF','id_status' => '5','description' => 'Infância Controle PF','start_date' => '2017-01-06','end_date' => '2017-07-05',],
28=> ['name' => 'Alteração de Nomes de Menus e Página - Meu Vivo Fixo Web','id_status' => '5','description' => 'Alteração de Nomes de Menus e Página - Meu Vivo Fixo Web','start_date' => '2017-01-06','end_date' => '2017-07-05',],
29=> ['name' => 'AlteraçãoTemplate E-mail Meu Vivo - Web/Site Mobile/ APP','id_status' => '5','description' => 'AlteraçãoTemplate E-mail Meu Vivo - Web/Site Mobile/ APP','start_date' => '2017-01-06','end_date' => '2017-07-05',],
30=> ['name' => '[#DEx - B2B Billing] Débito Automático - Envio SMS para Gestor PJ','id_status' => '5','description' => '[#DEx - B2B Billing] Débito Automático - Envio SMS para Gestor PJ','start_date' => '2017-01-09','end_date' => '2017-07-08',],
31=> ['name' => '[#DEx - B2B Billing] Nova Jornada Informe de Pagamento PJ - Móvel','id_status' => '5','description' => '[#DEx - B2B Billing] Nova Jornada Informe de Pagamento PJ - Móvel','start_date' => '2017-01-09','end_date' => '2017-07-08',],
32=> ['name' => '[DEX B2B Billing] Alteração de endereço de cobrança Meu Vivo Web PJ - Móvel','id_status' => '5','description' => '[DEX B2B Billing] Alteração de endereço de cobrança Meu Vivo Web PJ - Móvel','start_date' => '2017-01-09','end_date' => '2017-07-08',],
33=> ['name' => 'Tempo de Carregamento - Portal','id_status' => '5','description' => 'Tempo de Carregamento - Portal','start_date' => '2017-01-09','end_date' => '2017-07-08',],
34=> ['name' => 'Projeto Desligue Datacenters (CIS  PV  LP)','id_status' => '5','description' => 'Projeto Desligue Datacenters (CIS  PV  LP)','start_date' => '2017-01-10','end_date' => '2017-07-09',],
35=> ['name' => 'Plano de Capacidade - 2017 - Vivonet','id_status' => '5','description' => 'Plano de Capacidade - 2017 - Vivonet','start_date' => '2017-01-10','end_date' => '2017-07-09',],
36=> ['name' => 'Troca do servidor GSDB001','id_status' => '5','description' => 'Troca do servidor GSDB001','start_date' => '2017-01-11','end_date' => '2017-07-10',],
37=> ['name' => 'Revisão Usabilidade Home do Login Meu Vivo','id_status' => '5','description' => 'Revisão Usabilidade Home do Login Meu Vivo','start_date' => '2017-01-11','end_date' => '2017-07-10',],
38=> ['name' => 'Troca de Layout Erro 404 Portal Vivo - Mobile','id_status' => '5','description' => 'Troca de Layout Erro 404 Portal Vivo - Mobile','start_date' => '2017-01-12','end_date' => '2017-07-11',],
39=> ['name' => 'Disponibilização Pontos de Controle Atlys no MM','id_status' => '5','description' => 'Disponibilização Pontos de Controle Atlys no MM','start_date' => '2017-01-12','end_date' => '2017-07-11',],
40=> ['name' => 'Criação de User Area do DW Teradata','id_status' => '5','description' => 'Criação de User Area do DW Teradata','start_date' => '2017-01-12','end_date' => '2017-07-11',],
41=> ['name' => 'Simplificação do Processo de Ativação Pré-Pago','id_status' => '5','description' => 'Simplificação do Processo de Ativação Pré-Pago','start_date' => '2017-01-10','end_date' => '2017-07-09',],
42=> ['name' => 'Oferta Convergente','id_status' => '5','description' => 'Oferta Convergente','start_date' => '2017-01-10','end_date' => '2017-07-09',],
43=> ['name' => 'NOF ¿ Notification Observer Framework','id_status' => '5','description' => 'NOF ¿ Notification Observer Framework','start_date' => '2017-01-11','end_date' => '2017-07-10',],
44=> ['name' => 'Intragov - Upgrade de infra do SGOE','id_status' => '5','description' => 'Intragov - Upgrade de infra do SGOE','start_date' => '2017-01-11','end_date' => '2017-07-10',],
45=> ['name' => 'EOC e SGT - Plano de Obsolescência 2017','id_status' => '5','description' => 'EOC e SGT - Plano de Obsolescência 2017','start_date' => '2017-01-12','end_date' => '2017-07-11',],
46=> ['name' => 'Alteração Formulário C2C','id_status' => '5','description' => 'Alteração Formulário C2C','start_date' => '2017-01-12','end_date' => '2017-07-11',],
47=> ['name' => 'UnFrida B2B','id_status' => '5','description' => 'UnFrida B2B','start_date' => '2017-01-12','end_date' => '2017-07-11',],
48=> ['name' => 'PJ NEW- Transferencia de Arquivos Retenção','id_status' => '5','description' => 'PJ NEW- Transferencia de Arquivos Retenção','start_date' => '2017-01-13','end_date' => '2017-07-12',],
49=> ['name' => 'Troca da infra do servidor GSDB001','id_status' => '5','description' => 'Troca da infra do servidor GSDB001','start_date' => '2017-01-13','end_date' => '2017-07-12',],
50=> ['name' => 'Evolução do Movimento de Saldo Detalhado DW','id_status' => '5','description' => 'Evolução do Movimento de Saldo Detalhado DW','start_date' => '2017-01-13','end_date' => '2017-07-12',],
51=> ['name' => 'Troca de servidor GSDB001','id_status' => '5','description' => 'Troca de servidor GSDB001','start_date' => '2017-01-13','end_date' => '2017-07-12',],
52=> ['name' => 'Novos Alertas URA Móvel','id_status' => '5','description' => 'Novos Alertas URA Móvel','start_date' => '2017-01-13','end_date' => '2017-07-12',],
53=> ['name' => 'Geração de Relatorio TUPTRAF  Oficio 47  Clearing','id_status' => '5','description' => 'Geração de Relatorio TUPTRAF  Oficio 47  Clearing','start_date' => '2017-01-13','end_date' => '2017-07-12',],
54=> ['name' => 'Integração SITTEL MPPB','id_status' => '5','description' => 'Integração SITTEL MPPB','start_date' => '2017-01-16','end_date' => '2017-07-15',],
55=> ['name' => 'DIRF 2017','id_status' => '5','description' => 'DIRF 2017','start_date' => '2017-01-17','end_date' => '2017-07-16',],
56=> ['name' => 'Mudança de Marca da MAIS AD na URA MVNO','id_status' => '5','description' => 'Mudança de Marca da MAIS AD na URA MVNO','start_date' => '2017-01-17','end_date' => '2017-07-16',],
57=> ['name' => '[WO] Novas Sub-Areas Medidas e Consignado','id_status' => '5','description' => '[WO] Novas Sub-Areas Medidas e Consignado','start_date' => '2017-01-17','end_date' => '2017-07-16',],
58=> ['name' => 'Projeto Dados + Segurança','id_status' => '5','description' => 'Projeto Dados + Segurança','start_date' => '2017-01-18','end_date' => '2017-07-17',],
59=> ['name' => 'Implantação Novo Distribuidor de Recargas - TBC Serviços.','id_status' => '5','description' => 'Implantação Novo Distribuidor de Recargas - TBC Serviços.','start_date' => '2017-01-18','end_date' => '2017-07-17',],
60=> ['name' => 'Implantação Novo Distribuidor de Recargas TBC Serviços','id_status' => '5','description' => 'Implantação Novo Distribuidor de Recargas TBC Serviços','start_date' => '2017-01-18','end_date' => '2017-07-17',],
61=> ['name' => 'Adequação preço ¿ Planos Controle PJ - SP','id_status' => '5','description' => 'Adequação preço ¿ Planos Controle PJ - SP','start_date' => '2017-01-16','end_date' => '2017-07-15',],
62=> ['name' => '[DEX B2C Gestão Saldo] Disponibilizar consumo de minutos e SMS','id_status' => '5','description' => '[DEX B2C Gestão Saldo] Disponibilizar consumo de minutos e SMS','start_date' => '2017-01-16','end_date' => '2017-07-15',],
63=> ['name' => '[DEX B2C Gestão Saldo] Revitalização do consumo de internet','id_status' => '5','description' => '[DEX B2C Gestão Saldo] Revitalização do consumo de internet','start_date' => '2017-01-16','end_date' => '2017-07-15',],
64=> ['name' => '[DEX B2C Gestão Saldo] Disponibilizar o contrato SMP assinado pelo cliente e o regulamento do plano','id_status' => '5','description' => '[DEX B2C Gestão Saldo] Disponibilizar o contrato SMP assinado pelo cliente e o regulamento do plano','start_date' => '2017-01-16','end_date' => '2017-07-15',],
65=> ['name' => 'Implantação Novo Distribuidor de Recargas - TBC Serviços','id_status' => '5','description' => 'Implantação Novo Distribuidor de Recargas - TBC Serviços','start_date' => '2017-01-17','end_date' => '2017-07-16',],
66=> ['name' => 'Plano de Capacidade - 2017 - Sigres DM','id_status' => '5','description' => 'Plano de Capacidade - 2017 - Sigres DM','start_date' => '2017-01-17','end_date' => '2017-07-16',],
67=> ['name' => 'Incentivo Antecipação Vivo Turbo','id_status' => '5','description' => 'Incentivo Antecipação Vivo Turbo - Fase 2','start_date' => '2017-01-18','end_date' => '2017-07-17',],
68=> ['name' => 'Alteração Palito Contestação - Módulo de Contestação','id_status' => '5','description' => 'Alteração Palito Contestação - Módulo de Contestação','start_date' => '2017-01-18','end_date' => '2017-07-17',],
69=> ['name' => 'Envio de 2ª via de Fatura pela URA da Fixa','id_status' => '5','description' => 'Envio de 2ª via de Fatura pela URA da Fixa','start_date' => '2017-01-18','end_date' => '2017-07-17',],
70=> ['name' => 'Realizar troca do servidor GSDB001','id_status' => '5','description' => 'Realizar troca do servidor GSDB001','start_date' => '2017-01-19','end_date' => '2017-07-18',],
71=> ['name' => 'Atualização do DC da Vivo 2','id_status' => '5','description' => 'Atualização do DC da Vivo 2','start_date' => '2017-01-19','end_date' => '2017-07-18',],
72=> ['name' => 'Criar tela para consulta de eventos sem sucesso','id_status' => '5','description' => 'Criar tela para consulta de eventos sem sucesso','start_date' => '2017-01-19','end_date' => '2017-07-18',],
73=> ['name' => 'Migração Plataforma Pré-Pago Fixa','id_status' => '5','description' => 'Migração Plataforma Pré-Pago Fixa','start_date' => '2017-01-19','end_date' => '2017-07-18',],
74=> ['name' => 'Criar tela para consulta de tarifação sem sucesso','id_status' => '5','description' => 'Criar tela para consulta de tarifação sem sucesso','start_date' => '2017-01-19','end_date' => '2017-07-18',],
75=> ['name' => 'Biometria de Voz - Cadastro de Agente','id_status' => '5','description' => 'Biometria de Voz - Cadastro de Agente','start_date' => '2017-01-19','end_date' => '2017-07-18',],
76=> ['name' => 'Tratativa Backlog Gestores não sincronizado - VivoCorp x VivoNet','id_status' => '5','description' => 'Tratativa Backlog Gestores não sincronizado - VivoCorp x VivoNet','start_date' => '2017-01-23','end_date' => '2017-07-22',],
77=> ['name' => 'Projeto Concordia - Solicitação de Ambiente para sistema PPM','id_status' => '5','description' => 'Projeto Concordia - Solicitação de Ambiente para sistema PPM','start_date' => '2017-01-23','end_date' => '2017-07-22',],
78=> ['name' => 'Implantação Sand Box','id_status' => '5','description' => 'Implantação Sand Box','start_date' => '2017-01-23','end_date' => '2017-07-22',],
79=> ['name' => '[DEX B2C Billing eBilling] Transformação Conta Digital Release Junho','id_status' => '5','description' => '[DEX B2C Billing eBilling] Transformação Conta Digital Release Junho','start_date' => '2017-01-20','end_date' => '2017-07-19',],
80=> ['name' => 'Atualização de Bancos Débito Automático- Meu Vivo','id_status' => '5','description' => 'Atualização de Bancos Débito Automático- Meu Vivo','start_date' => '2017-01-20','end_date' => '2017-07-19',],
81=> ['name' => 'SVAs On Top Of (Planos Controle)','id_status' => '5','description' => 'SVAs On Top Of (Planos Controle)','start_date' => '2017-01-20','end_date' => '2017-07-19',],
82=> ['name' => 'Integração entre BMC Remedy ITSM (VIVO) x UTS (AMDOCS)','id_status' => '5','description' => 'Integração entre BMC Remedy ITSM (VIVO) x UTS (AMDOCS)','start_date' => '2017-01-23','end_date' => '2017-07-22',],
83=> ['name' => 'PC17 - Ngin / CARE ¿ BASE A OBSOLESCENCIA SISTEMA OPERACIONAL','id_status' => '5','description' => 'PC17 - Ngin / CARE ¿ BASE A OBSOLESCENCIA SISTEMA OPERACIONAL','start_date' => '2017-01-23','end_date' => '2017-07-22',],
84=> ['name' => 'PC17 - Ngin / CARE ¿ BASE A UPGRADE','id_status' => '5','description' => 'PC17 - Ngin / CARE ¿ BASE A UPGRADE','start_date' => '2017-01-23','end_date' => '2017-07-22',],
85=> ['name' => 'PC17 - Ngin / CORE - OPEN CALL OBSOLESCENCIA','id_status' => '5','description' => 'PC17 - Ngin / CORE - OPEN CALL OBSOLESCENCIA','start_date' => '2017-01-23','end_date' => '2017-07-22',],
86=> ['name' => 'Contestação de contas PF através da aplicação ATLYS','id_status' => '5','description' => 'Contestação de contas PF através da aplicação ATLYS','start_date' => '2017-01-23','end_date' => '2017-07-22',],
87=> ['name' => 'Inclusão Frida para Planos antigos Pós - Quebra de Charges','id_status' => '5','description' => 'Inclusão Frida para Planos antigos Pós - Quebra de Charges','start_date' => '2017-01-24','end_date' => '2017-07-23',],
88=> ['name' => 'Ação Migração Portfólios Antigos Controle','id_status' => '5','description' => 'Ação Migração Portfólios Antigos Controle','start_date' => '2017-01-24','end_date' => '2017-07-23',],
89=> ['name' => 'Portal BeFlex - Autenticação via OAM','id_status' => '5','description' => 'Portal BeFlex - Autenticação via OAM','start_date' => '2017-01-24','end_date' => '2017-07-23',],
90=> ['name' => 'Melhorias EH&S  PA e PT','id_status' => '5','description' => 'Melhorias EH&S  PA e PT','start_date' => '2017-01-24','end_date' => '2017-07-23',],
91=> ['name' => 'Gestão de Terceiros  PA e BN','id_status' => '5','description' => 'Gestão de Terceiros  PA e BN','start_date' => '2017-01-24','end_date' => '2017-07-23',],
92=> ['name' => 'Melhorias Ambiente de Homologação e Desenvolvimento Pro-Siga 2','id_status' => '5','description' => 'Melhorias Ambiente de Homologação e Desenvolvimento Pro-Siga 2','start_date' => '2017-01-26','end_date' => '2017-07-25',],
93=> ['name' => 'Placa Combo 2x10GE + 4x1GE (ALCATEL/NOKIA) para Rede Metroethernet São Paulo','id_status' => '5','description' => 'Placa Combo 2x10GE + 4x1GE (ALCATEL/NOKIA) para Rede Metroethernet São Paulo','start_date' => '2017-01-26','end_date' => '2017-07-25',],
94=> ['name' => 'Default PJ','id_status' => '5','description' => 'Default PJ','start_date' => '2017-01-26','end_date' => '2017-07-25',],
95=> ['name' => 'Ambiente Homologação ¿ Massivo FRAUDEVIEW','id_status' => '5','description' => 'Ambiente Homologação ¿ Massivo FRAUDEVIEW','start_date' => '2017-01-26','end_date' => '2017-07-25',],
96=> ['name' => 'Adição de ambiente de desenvolvimento - Intranet Corporativa','id_status' => '5','description' => 'Adição de ambiente de desenvolvimento - Intranet Corporativa','start_date' => '2017-01-26','end_date' => '2017-07-25',],
97=> ['name' => 'Adição de ambiente de desenvolvimento - Nova Intranet Corporativa','id_status' => '5','description' => 'Adição de ambiente de desenvolvimento - Nova Intranet Corporativa','start_date' => '2017-01-26','end_date' => '2017-07-25',],
98=> ['name' => 'Majoração ICMS 2017','id_status' => '5','description' => 'Majoração ICMS 2017','start_date' => '2017-01-27','end_date' => '2017-07-26',],
99=> ['name' => 'Processo de Monitoração - Arrecadação e Cobrança ATLYS / ATIS / Legados','id_status' => '5','description' => 'Processo de Monitoração - Arrecadação e Cobrança ATLYS / ATIS / Legados','start_date' => '2017-01-24','end_date' => '2017-07-23',],
100=> ['name' => 'BIG DATA ¿ DPI SIG ¿ Melhorias para micro-segmentação','id_status' => '5','description' => 'BIG DATA ¿ DPI SIG ¿ Melhorias para micro-segmentação','start_date' => '2017-01-24','end_date' => '2017-07-23',],
101=> ['name' => '[WO] Melhorias de Time e Folha de Pagamento','id_status' => '5','description' => '[WO] Melhorias de Time e Folha de Pagamento','start_date' => '2017-01-24','end_date' => '2017-07-23',],
102=> ['name' => '[DEX Web APP PF] Multivivo - Controle das franquias de dados pelo titular','id_status' => '5','description' => '[DEX Web APP PF] Multivivo - Controle das franquias de dados pelo titular','start_date' => '2017-01-24','end_date' => '2017-07-23',],
103=> ['name' => 'Gauss - Previsibilidade - Controle de Tráfego','id_status' => '5','description' => 'Gauss - Previsibilidade - Controle de Tráfego','start_date' => '2017-01-27','end_date' => '2017-07-26',],
104=> ['name' => 'Adequações e Melhorias Sittel','id_status' => '5','description' => 'Adequações e Melhorias Sittel','start_date' => '2017-01-30','end_date' => '2017-07-29',],
105=> ['name' => 'Quick Wins Processum','id_status' => '5','description' => 'Quick Wins Processum','start_date' => '2017-01-30','end_date' => '2017-07-29',],
106=> ['name' => 'Criação do Novo Backend do Meu Vivo App.','id_status' => '5','description' => 'Criação do Novo Backend do Meu Vivo App.','start_date' => '2017-01-27','end_date' => '2017-07-26',],
107=> ['name' => 'Melhoria processo aviso de férias','id_status' => '5','description' => 'Melhoria processo aviso de férias','start_date' => '2017-01-27','end_date' => '2017-07-26',],
108=> ['name' => 'Overview Sistema Vivocorp','id_status' => '5','description' => 'Overview Sistema Vivocorp','start_date' => '2017-01-30','end_date' => '2017-07-29',],
109=> ['name' => 'Refresh de Dados - Vivo Turbo','id_status' => '5','description' => 'Refresh de Dados - Vivo Turbo','start_date' => '2017-01-30','end_date' => '2017-07-29',],
110=> ['name' => 'Novo Vivo Gestão B2B','id_status' => '5','description' => 'Novo Vivo Gestão B2B','start_date' => '2017-01-30','end_date' => '2017-07-29',],
111=> ['name' => 'Torpedo Empresas','id_status' => '5','description' => 'Novas Faixas de Preço TE','start_date' => '2017-01-31','end_date' => '2017-07-30',],
112=> ['name' => 'transbordo das atividades de conferência de contratos / aditivos','id_status' => '5','description' => 'transbordo das atividades de conferência de contratos / aditivos','start_date' => '2017-01-31','end_date' => '2017-07-30',],
113=> ['name' => 'Atualização Tecnologica dos Servidores de Banco de Dados do SAP e Remoção do Veritas','id_status' => '5','description' => 'Atualização Tecnologica dos Servidores de Banco de Dados do SAP e Remoção do Veritas','start_date' => '2017-01-31','end_date' => '2017-07-30',],
114=> ['name' => 'Ambiente Portabilidade FIXA - Esteira Pre-prod QA','id_status' => '5','description' => 'Ambiente Portabilidade FIXA - Esteira Pre-prod QA','start_date' => '2017-02-01','end_date' => '2017-07-31',],
115=> ['name' => 'Segurança - Projeto Eliot','id_status' => '5','description' => 'Segurança - Projeto Eliot','start_date' => '2017-01-31','end_date' => '2017-07-30',],
116=> ['name' => 'Atualização Tecnológica dos Servidores de Banco de Dados do SAP e Remoção do Veritas','id_status' => '5','description' => 'Atualização Tecnológica dos Servidores de Banco de Dados do SAP e Remoção do Veritas','start_date' => '2017-01-31','end_date' => '2017-07-30',],
117=> ['name' => 'Relatórios Financeiros REPNBL Onerados e Desonerados','id_status' => '5','description' => 'Relatórios Financeiros REPNBL Onerados e Desonerados','start_date' => '2017-01-31','end_date' => '2017-07-30',],
118=> ['name' => 'Compartilhamento de Dados Vivo Turbo','id_status' => '5','description' => 'Compartilhamento de Dados Vivo Turbo','start_date' => '2017-02-01','end_date' => '2017-07-31',],
119=> ['name' => '[Beatrix - Migração] ¿ Bill to Bill','id_status' => '5','description' => '[Beatrix - Migração] ¿ Bill to Bill','start_date' => '2017-02-01','end_date' => '2017-07-31',],
120=> ['name' => 'Alteração Contagem Prazo Acionamento Réguas de Cobrança','id_status' => '5','description' => 'Alteração Contagem Prazo Acionamento Réguas de Cobrança','start_date' => '2017-02-01','end_date' => '2017-07-31',],
121=> ['name' => 'Alteração de Tributos - Estado de Minas Gerais','id_status' => '5','description' => 'Alteração de Tributos - Estado de Minas Gerais','start_date' => '2017-02-01','end_date' => '2017-07-31',],
122=> ['name' => 'EVA ¿ Migração Incentivada','id_status' => '5','description' => 'EVA ¿ Migração Incentivada','start_date' => '2017-02-01','end_date' => '2017-07-31',],
123=> ['name' => 'Criação de Ambiente não produtivos do Connector(Portabilidade)','id_status' => '5','description' => 'Criação de Ambiente não produtivos do Connector(Portabilidade)','start_date' => '2017-02-02','end_date' => '2017-08-01',],
124=> ['name' => 'Ofertas GVT - Clientes Vivo 1 ¿ Fase II Banda Larga','id_status' => '5','description' => 'Ofertas GVT - Clientes Vivo 1 ¿ Fase II Banda Larga','start_date' => '2017-02-02','end_date' => '2017-08-01',],
125=> ['name' => 'Relatórios de apoio Previdência Privada','id_status' => '5','description' => 'Relatórios de apoio Previdência Privada','start_date' => '2017-02-02','end_date' => '2017-08-01',],
126=> ['name' => 'Desoneração ISS TDATA - Fase 2','id_status' => '5','description' => 'Desoneração ISS TDATA - Fase 2','start_date' => '2017-02-02','end_date' => '2017-08-01',],
127=> ['name' => 'DUMP Vivonet Ambiente de QA','id_status' => '5','description' => 'DUMP Vivonet Ambiente de QA','start_date' => '2017-02-02','end_date' => '2017-08-01',],
128=> ['name' => 'Simplificação Processo de Ativação Pré-Pago','id_status' => '5','description' => 'Simplificação Processo de Ativação Pré-Pago','start_date' => '2017-02-02','end_date' => '2017-08-01',],
129=> ['name' => 'Benefício Fiscal - Estado de Rondônia','id_status' => '5','description' => 'Benefício Fiscal - Estado de Rondônia','start_date' => '2017-02-03','end_date' => '2017-08-02',],
130=> ['name' => 'Inclusão informações SVA Parceiros','id_status' => '5','description' => 'Inclusão informações SVA Parceiros','start_date' => '2017-02-03','end_date' => '2017-08-02',],
131=> ['name' => 'Plano de Capacidade - 2017 - GDOC','id_status' => '5','description' => 'Plano de Capacidade - 2017 - GDOC','start_date' => '2017-02-03','end_date' => '2017-08-02',],
132=> ['name' => 'Melhorias ACM','id_status' => '5','description' => 'Melhorias ACM','start_date' => '2017-02-06','end_date' => '2017-08-05',],
133=> ['name' => 'Criação do Novo Backend do Meu Vivo App','id_status' => '5','description' => 'Criação do Novo Backend do Meu Vivo App','start_date' => '2017-02-06','end_date' => '2017-08-05',],
134=> ['name' => 'Redução VUM 2017 - Plano Básico VC1 VC2 e VC3 SMP - Template 6BN','id_status' => '5','description' => 'Redução VUM 2017 - Plano Básico VC1 VC2 e VC3 SMP - Template 6BN','start_date' => '2017-02-06','end_date' => '2017-08-05',],
135=> ['name' => 'Acesso Direct Conectt - Correios','id_status' => '5','description' => 'Acesso Direct Conectt - Correios','start_date' => '2017-02-06','end_date' => '2017-08-05',],
136=> ['name' => 'Downgrade para Inadimplentes (PF Vivo 1) - Caixa Postal','id_status' => '5','description' => 'Downgrade para Inadimplentes (PF Vivo 1) - Caixa Postal','start_date' => '2017-02-03','end_date' => '2017-08-02',],
137=> ['name' => 'Alteração de alíquotas de ICMS','id_status' => '5','description' => 'Alteração de alíquotas de ICMS','start_date' => '2017-02-03','end_date' => '2017-08-02',],
138=> ['name' => 'Ocultar Menu Conta Digital - Meu Vivo PF FIXA','id_status' => '5','description' => 'Ocultar Menu Conta Digital - Meu Vivo PF FIXA','start_date' => '2017-02-03','end_date' => '2017-08-02',],
139=> ['name' => 'Melhorias NGIN BIT','id_status' => '5','description' => 'Melhorias NGIN BIT','start_date' => '2017-02-06','end_date' => '2017-08-05',],
140=> ['name' => 'Downgrade para Inadimplentes (PF Vivo 1) Caixa Postal','id_status' => '5','description' => 'Downgrade para Inadimplentes (PF Vivo 1) Caixa Postal','start_date' => '2017-02-06','end_date' => '2017-08-05',],
141=> ['name' => '[Projeto SOPHIA] Migração Massiva - Juros Multa e Termo de Quitação','id_status' => '5','description' => '[Projeto SOPHIA] Migração Massiva - Juros Multa e Termo de Quitação','start_date' => '2017-02-06','end_date' => '2017-08-05',],
142=> ['name' => 'Refresh Técnológico: Servidores Departamentais','id_status' => '5','description' => 'Refresh Técnológico: Servidores Departamentais','start_date' => '2017-02-06','end_date' => '2017-08-05',],
143=> ['name' => 'NGIN Digital - One Click to Buy','id_status' => '5','description' => 'NGIN Digital - One Click to Buy','start_date' => '2017-02-06','end_date' => '2017-08-05',],
144=> ['name' => 'PJ NEW - URA da Qualidade Genesys','id_status' => '5','description' => 'PJ NEW - URA da Qualidade Genesys','start_date' => '2017-02-07','end_date' => '2017-08-06',],
145=> ['name' => 'Integração entre BMC Remedy ITSM (VIVO) x UTS (AMDOCS) - Amb Produção','id_status' => '5','description' => 'Integração entre BMC Remedy ITSM (VIVO) x UTS (AMDOCS) - Amb Produção','start_date' => '2017-02-07','end_date' => '2017-08-06',],
146=> ['name' => 'Amb Produção - Integração entre BMC Remedy ITSM (VIVO) x UTS (AMDOCS)','id_status' => '5','description' => 'Amb Produção - Integração entre BMC Remedy ITSM (VIVO) x UTS (AMDOCS)','start_date' => '2017-02-07','end_date' => '2017-08-06',],
147=> ['name' => 'Melhorias no módulo da Retenção Fixa PJ (Big ML)','id_status' => '5','description' => 'Melhorias no módulo da Retenção Fixa PJ (Big ML)','start_date' => '2017-02-07','end_date' => '2017-08-06',],






        ];
        DB::table('sc_project')->insert($sc_project);
    }

}
